import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { ThemeProvider } from 'styled-components';
import { userEvent } from 'vitest/browser';
import { afterEach, describe, expect, it, vi } from 'vitest';

import type { PersistedStoreConfig } from '../../hooks/useConfig';
import { darkTheme } from '../../theme/theme';
import { normalizeStoreConfig, withStoreDefaults } from './modelStoreConfig';
import { SettingsPanel } from './SettingsPanel';

Object.defineProperty(globalThis, 'IS_REACT_ACT_ENVIRONMENT', { value: true, configurable: true });

const useConfigMock = vi.hoisted(() => vi.fn());
const dispatchMock = vi.hoisted(() => vi.fn());

vi.mock('../../hooks/useConfig', () => ({
  useConfig: useConfigMock,
}));

vi.mock('../../store/hooks', () => ({
  useAppDispatch: () => dispatchMock,
  useAppSelector: () => 'dark',
}));

vi.mock('../../i18n/tolgee', () => ({
  useSkulkTranslation: () => ({
    t: (_key: string, fallback: string) => fallback,
  }),
}));

vi.mock('../../hooks/useToast', () => ({
  addToast: vi.fn(),
}));

vi.mock('./DevicesPanel', () => ({ DevicesPanel: () => <div>Device actions fixture</div> }));

vi.mock('./PairingSettings', () => ({
  PairingSettings: () => <div>Pairing</div>,
}));

let root: Root | null = null;
let container: HTMLDivElement | null = null;

afterEach(async () => {
  await act(async () => root?.unmount());
  container?.remove();
  root = null;
  container = null;
  // Section expansion persists in storage; a test that fails before its own
  // cleanup must not open or close sections for the next one.
  localStorage.removeItem('skulk-settings-sections');
  vi.unstubAllGlobals();
  vi.clearAllMocks();
});

describe('normalizeStoreConfig', () => {
  it('materializes server defaults for a sparse installer-generated section', () => {
    const persisted: PersistedStoreConfig = {
      store_host: 'fresh-node',
      store_http_host: '127.0.0.1',
      store_port: 12415,
      store_path: '/tmp/model-store',
    };

    expect(normalizeStoreConfig(persisted)).toEqual({
      enabled: true,
      store_host: 'fresh-node',
      store_http_host: '127.0.0.1',
      store_port: 12415,
      store_path: '/tmp/model-store',
      download: {
        allow_hf_fallback: true,
      },
      staging: {
        enabled: true,
        node_cache_path: '~/.skulk/staging',
        cleanup_on_deactivate: true,
      },
    });
  });

  it('keeps an absent model-store section disabled', () => {
    expect(normalizeStoreConfig(null).enabled).toBe(false);
  });
});

const STORE_DEFAULTS = {
  store_host: 'kite-dev',
  store_port: 12415,
  store_http_host: '127.0.0.1',
  store_path: '/Users/operator/.skulk/model-store',
};

describe('withStoreDefaults', () => {
  it('fills a switched-on store from the node defaults', () => {
    const filled = withStoreDefaults({ ...normalizeStoreConfig(null), enabled: true }, STORE_DEFAULTS);
    expect(filled).toMatchObject({
      enabled: true,
      store_host: 'kite-dev',
      store_http_host: '127.0.0.1',
      store_path: '/Users/operator/.skulk/model-store',
    });
  });

  it('keeps what the operator typed, including the HTTP host of a named store host', () => {
    const typed = {
      ...normalizeStoreConfig(null),
      enabled: true,
      store_host: 'mac-studio',
      store_path: '/Volumes/Models',
    };
    expect(withStoreDefaults(typed, STORE_DEFAULTS)).toEqual(typed);
  });

  it('leaves a disabled store or a node without defaults unchanged', () => {
    const disabled = normalizeStoreConfig(null);
    expect(withStoreDefaults(disabled, STORE_DEFAULTS)).toEqual(disabled);
    const enabled = { ...disabled, enabled: true };
    expect(withStoreDefaults(enabled, undefined)).toEqual(enabled);
  });
});

describe('SettingsPanel persisted config handling', () => {
  it('renders Settings from the sparse config generated by the installer', async () => {
    useConfigMock.mockReturnValue({
      fullConfig: {
        model_store: {
          store_host: 'fresh-node',
          store_http_host: '127.0.0.1',
          store_port: 12415,
          store_path: '/tmp/model-store',
        },
      },
      effective: {
        kv_cache_backend: 'default',
        has_hf_token: false,
        experimental_mode_enabled: false,
      },
      configPath: '/tmp/skulk.yaml',
      loading: false,
      saving: false,
      error: null,
      fetchConfig: vi.fn(async () => undefined),
      saveFullConfig: vi.fn<(config: unknown) => Promise<boolean>>(async () => true),
    });
    container = document.createElement('div');
    document.body.append(container);
    root = createRoot(container);

    await act(async () => {
      root?.render(
        <ThemeProvider theme={darkTheme}>
          <SettingsPanel open onClose={vi.fn()} />
        </ThemeProvider>,
      );
    });

    expect(container.textContent).toContain('Settings');
    expect(container.textContent).toContain('Allow HuggingFace fallback');
    expect(
      container.querySelector<HTMLInputElement>('input[value="fresh-node"]'),
    ).not.toBeNull();
    expect(
      container.querySelector<HTMLInputElement>(
        'input[value="~/.skulk/staging"]',
      ),
    ).not.toBeNull();

    const portInput =
      container.querySelector<HTMLInputElement>('input[value="12415"]');
    expect(portInput).not.toBeNull();
    await act(async () => {
      const valueSetter = Object.getOwnPropertyDescriptor(
        HTMLInputElement.prototype,
        'value',
      )?.set;
      valueSetter?.call(portInput, '');
      portInput?.dispatchEvent(new Event('input', { bubbles: true }));
    });
    expect(portInput?.value).toBe('12415');
  });

  it('does not expose or persist the retired model-trust ceremony', async () => {
    const saveFullConfig = vi.fn<(config: unknown) => Promise<boolean>>(async () => true);
    const fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    useConfigMock.mockReturnValue({
      fullConfig: {
        model_trust: {
          approved_remote_code_identities: [`card_${'a'.repeat(52)}`],
        },
      },
      effective: {
        kv_cache_backend: 'default',
        has_hf_token: false,
        experimental_mode_enabled: false,
      },
      configPath: '/tmp/skulk.yaml',
      loading: false,
      saving: false,
      error: null,
      fetchConfig: vi.fn(async () => undefined),
      saveFullConfig,
    });
    container = document.createElement('div');
    document.body.append(container);
    root = createRoot(container);

    await act(async () => {
      root?.render(
        <ThemeProvider theme={darkTheme}>
          <SettingsPanel open onClose={vi.fn()} />
        </ThemeProvider>,
      );
    });

    expect(container.textContent).not.toContain('Model trust');
    const saveButton = [...container.querySelectorAll<HTMLButtonElement>('button')]
      .find((button) => button.textContent === 'Save changes');
    expect(saveButton).toBeDefined();
    await act(async () => {
      saveButton?.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    });

    expect(saveFullConfig).toHaveBeenCalledOnce();
    expect(saveFullConfig.mock.calls[0]?.[0]).not.toHaveProperty('model_trust');
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it('fills a newly enabled store with the node defaults and saves them', async () => {
    localStorage.setItem('skulk-settings-sections', JSON.stringify({ modelStore: true }));
    const saveFullConfig = vi.fn<(config: unknown) => Promise<boolean>>(async () => true);
    useConfigMock.mockReturnValue({
      fullConfig: {},
      effective: {
        kv_cache_backend: 'default',
        has_hf_token: false,
        experimental_mode_enabled: false,
        model_store_defaults: STORE_DEFAULTS,
      },
      configPath: 'skulk.yaml',
      loading: false,
      saving: false,
      error: null,
      fetchConfig: vi.fn(async () => undefined),
      saveFullConfig,
    });
    container = document.createElement('div');
    document.body.append(container);
    root = createRoot(container);
    await act(async () => {
      root?.render(
        <ThemeProvider theme={darkTheme}>
          <SettingsPanel open onClose={vi.fn()} />
        </ThemeProvider>,
      );
    });

    const storeSection = [...container.querySelectorAll('details')]
      .find((details) => details.querySelector('summary')?.textContent?.startsWith('Model Store'));
    expect(storeSection).toBeDefined();
    const toggle = storeSection?.querySelector<HTMLElement>('[aria-label="Enabled"]');
    await act(async () => {
      toggle?.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    });

    expect(container.querySelector<HTMLInputElement>('input[value="kite-dev"]')).not.toBeNull();
    expect(
      container.querySelector<HTMLInputElement>('input[value="/Users/operator/.skulk/model-store"]'),
    ).not.toBeNull();
    const saveButton = [...container.querySelectorAll<HTMLButtonElement>('button')]
      .find((button) => button.textContent === 'Save changes');
    await act(async () => {
      saveButton?.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    });

    expect(saveFullConfig).toHaveBeenCalledOnce();
    expect(saveFullConfig.mock.calls[0]?.[0]).toMatchObject({
      model_store: {
        enabled: true,
        store_host: 'kite-dev',
        store_http_host: '127.0.0.1',
        store_path: '/Users/operator/.skulk/model-store',
      },
    });
    localStorage.removeItem('skulk-settings-sections');
  });

  it('saves the served context default and keeps the rest of the inference section', async () => {
    localStorage.setItem('skulk-settings-sections', JSON.stringify({ inference: true }));
    const saveFullConfig = vi.fn<(config: unknown) => Promise<boolean>>(async () => true);
    useConfigMock.mockReturnValue({
      fullConfig: {
        inference: { kv_cache_backend: 'default', served_context_tokens: 65536, future_field: 'kept' },
      },
      effective: { kv_cache_backend: 'default', has_hf_token: false, experimental_mode_enabled: false },
      configPath: '/tmp/skulk.yaml',
      loading: false,
      saving: false,
      error: null,
      fetchConfig: vi.fn(async () => undefined),
      saveFullConfig,
    });
    container = document.createElement('div');
    document.body.append(container);
    root = createRoot(container);
    await act(async () => {
      root?.render(
        <ThemeProvider theme={darkTheme}>
          <SettingsPanel open onClose={vi.fn()} />
        </ThemeProvider>,
      );
    });

    const field = container.querySelector<HTMLInputElement>('input[aria-label="Default served context (tokens)"]');
    expect(field?.value).toBe('65536');
    await userEvent.clear(field!);
    await userEvent.type(field!, '16384');
    const saveButton = [...container.querySelectorAll<HTMLButtonElement>('button')]
      .find((button) => button.textContent === 'Save changes');
    await act(async () => {
      saveButton?.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    });

    expect(saveFullConfig).toHaveBeenCalledOnce();
    expect(saveFullConfig.mock.calls[0]?.[0]).toMatchObject({
      inference: { kv_cache_backend: 'default', served_context_tokens: 16384, future_field: 'kept' },
    });
    localStorage.removeItem('skulk-settings-sections');
  });

});

it('preserves an unsaved draft across Devices and commits it only with Save', async () => {
  const saveFullConfig = vi.fn<(config: unknown) => Promise<boolean>>(async () => true);
  useConfigMock.mockReturnValue({ fullConfig: { hf_token: '' }, effective: { kv_cache_backend: 'default', has_hf_token: false }, loading: false, saving: false, error: null, fetchConfig: vi.fn(), saveFullConfig });
  // Open the section through its persisted preference, as the panel restores
  // it, rather than by clicking its summary: the draft is the subject here,
  // and once on a loaded CI runner the token field stayed hidden after that
  // click until the test timed out.
  localStorage.setItem('skulk-settings-sections', JSON.stringify({ huggingFace: true }));
  container = document.createElement('div'); document.body.append(container); root = createRoot(container);
  await act(async () => root?.render(<ThemeProvider theme={darkTheme}><SettingsPanel open onClose={vi.fn()} /></ThemeProvider>));
  const section = [...container.querySelectorAll('summary')].find(summary => summary.textContent?.includes('HuggingFace'))!;
  expect(section.parentElement?.hasAttribute('open')).toBe(true);
  const token = container.querySelector<HTMLInputElement>('input[type="password"]')!;
  await userEvent.fill(token, 'fixture-unsaved-token');
  const devices = [...container.querySelectorAll('button')].find(button => button.getAttribute('aria-label') === 'Devices & pairing')!;
  await userEvent.click(devices);
  expect(container.textContent).toContain('Device actions fixture');
  expect(saveFullConfig).not.toHaveBeenCalled();
  const back = [...container.querySelectorAll('button')].find(button => button.getAttribute('aria-label') === 'Back to Settings')!;
  await userEvent.click(back);
  expect(container.querySelector<HTMLInputElement>('input[type="password"]')?.value).toBe('fixture-unsaved-token');
  expect(saveFullConfig).not.toHaveBeenCalled();
  await userEvent.click([...container.querySelectorAll('button')].find(button => button.textContent === 'Save changes')!);
  expect(saveFullConfig).toHaveBeenCalledWith(expect.objectContaining({ hf_token: 'fixture-unsaved-token' }));
});
