import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { ThemeProvider } from 'styled-components';
import { afterEach, describe, expect, it, vi } from 'vitest';

import type { PersistedStoreConfig } from '../../hooks/useConfig';
import { darkTheme } from '../../theme/theme';
import { normalizeStoreConfig } from './modelStoreConfig';
import { SettingsPanel } from './SettingsPanel';

globalThis.IS_REACT_ACT_ENVIRONMENT = true;

const useConfigMock = vi.hoisted(() => vi.fn());
const dispatchMock = vi.hoisted(() => vi.fn());

vi.mock('../../hooks/useConfig', () => ({
  useConfig: useConfigMock,
}));

vi.mock('../../store/hooks', () => ({
  useAppDispatch: () => dispatchMock,
  useAppSelector: () => 'dark',
}));

vi.mock('../../i18n/tolgee', () => ({
  useSkulkTranslation: () => ({
    t: (_key: string, fallback: string) => fallback,
  }),
}));

vi.mock('../../hooks/useToast', () => ({
  addToast: vi.fn(),
}));

let root: Root | null = null;
let container: HTMLDivElement | null = null;

afterEach(async () => {
  await act(async () => root?.unmount());
  container?.remove();
  root = null;
  container = null;
  vi.clearAllMocks();
});

describe('normalizeStoreConfig', () => {
  it('materializes server defaults for a sparse installer-generated section', () => {
    const persisted: PersistedStoreConfig = {
      store_host: 'fresh-node',
      store_http_host: '127.0.0.1',
      store_port: 12415,
      store_path: '/tmp/model-store',
    };

    expect(normalizeStoreConfig(persisted)).toEqual({
      enabled: true,
      store_host: 'fresh-node',
      store_http_host: '127.0.0.1',
      store_port: 12415,
      store_path: '/tmp/model-store',
      download: {
        allow_hf_fallback: true,
      },
      staging: {
        enabled: true,
        node_cache_path: '~/.skulk/staging',
        cleanup_on_deactivate: true,
      },
    });
  });

  it('keeps an absent model-store section disabled', () => {
    expect(normalizeStoreConfig(null).enabled).toBe(false);
  });
});

describe('SettingsPanel persisted config handling', () => {
  it('renders Settings from the sparse config generated by the installer', async () => {
    useConfigMock.mockReturnValue({
      fullConfig: {
        model_store: {
          store_host: 'fresh-node',
          store_http_host: '127.0.0.1',
          store_port: 12415,
          store_path: '/tmp/model-store',
        },
      },
      effective: {
        kv_cache_backend: 'default',
        has_hf_token: false,
        experimental_mode_enabled: false,
      },
      configPath: '/tmp/skulk.yaml',
      loading: false,
      saving: false,
      error: null,
      fetchConfig: vi.fn(async () => undefined),
      saveFullConfig: vi.fn(async () => true),
    });
    container = document.createElement('div');
    document.body.append(container);
    root = createRoot(container);

    await act(async () => {
      root?.render(
        <ThemeProvider theme={darkTheme}>
          <SettingsPanel open onClose={vi.fn()} />
        </ThemeProvider>,
      );
    });

    expect(container.textContent).toContain('Settings');
    expect(container.textContent).toContain('Allow HuggingFace fallback');
    expect(
      container.querySelector<HTMLInputElement>('input[value="fresh-node"]'),
    ).not.toBeNull();
    expect(
      container.querySelector<HTMLInputElement>(
        'input[value="~/.skulk/staging"]',
      ),
    ).not.toBeNull();

    const portInput =
      container.querySelector<HTMLInputElement>('input[value="12415"]');
    expect(portInput).not.toBeNull();
    await act(async () => {
      const valueSetter = Object.getOwnPropertyDescriptor(
        HTMLInputElement.prototype,
        'value',
      )?.set;
      valueSetter?.call(portInput, '');
      portInput?.dispatchEvent(new Event('input', { bubbles: true }));
    });
    expect(portInput?.value).toBe('12415');
  });
});
