"""Stable identity and authorization foundations for remote operators.

The operator subsystem is intentionally separate from Skulk's event-sourced
inference state. Its durable identities and authorization journal have a
different consistency, confidentiality, and recovery contract.
"""

from skulk.operator.authority import (
    AuthorityCommitConflictError,
    AuthorityKeyProvider,
    AuthorityRecord,
    EncryptedAuthorityStore,
)
from skulk.operator.consensus import (
    AuthorityAcceptedMessage,
    AuthorityAcceptMessage,
    AuthorityBallot,
    AuthorityCatchUpRequestMessage,
    AuthorityCatchUpResponseMessage,
    AuthorityCommitMessage,
    AuthorityCommittedEntry,
    AuthorityConsensusConflictError,
    AuthorityConsensusError,
    AuthorityConsensusParticipant,
    AuthorityConsensusRepository,
    AuthorityConsensusSnapshot,
    AuthorityConsensusState,
    AuthorityEnvelopeError,
    AuthorityNetworkEnvelope,
    AuthorityPrepareMessage,
    AuthorityPromiseMessage,
    AuthorityRejectedMessage,
    AuthorityTransport,
    AuthorityVoteCollector,
    create_authority_envelope,
    verify_authority_envelope,
)
from skulk.operator.consensus_store import (
    AuthorityConsensusAlreadyInitializedError,
    AuthorityConsensusIntegrityError,
    AuthorityConsensusNotInitializedError,
    SqliteAuthorityConsensusRepository,
)
from skulk.operator.identity import (
    ClusterIdentityMaterial,
    ClusterPublicIdentity,
    NodeInstallationIdentity,
    OperatorIdentityRepository,
    create_cluster_identity,
)
from skulk.operator.replication import (
    AuthorityAppliedCommit,
    AuthorityCertificateError,
    AuthorityCommitDescriptor,
    AuthorityCommitPosition,
    AuthorityMember,
    AuthorityMembership,
    AuthorityQuorumCertificate,
    AuthorityVote,
    apply_quorum_certified_payload,
    authority_bootstrap_position,
    authority_commit_digest,
    authority_membership_digest,
    authority_payload_digest,
    create_authority_member,
    create_authority_vote,
    validate_authority_descriptor,
    verify_quorum_certificate,
)
from skulk.operator.transport import AuthorityChannelTransport

__all__ = [
    "AuthorityAcceptMessage",
    "AuthorityAcceptedMessage",
    "AuthorityAppliedCommit",
    "AuthorityBallot",
    "AuthorityCatchUpRequestMessage",
    "AuthorityCatchUpResponseMessage",
    "AuthorityChannelTransport",
    "AuthorityCertificateError",
    "AuthorityCommitMessage",
    "AuthorityCommitConflictError",
    "AuthorityCommitDescriptor",
    "AuthorityCommitPosition",
    "AuthorityCommittedEntry",
    "AuthorityConsensusAlreadyInitializedError",
    "AuthorityConsensusConflictError",
    "AuthorityConsensusError",
    "AuthorityConsensusIntegrityError",
    "AuthorityConsensusNotInitializedError",
    "AuthorityConsensusParticipant",
    "AuthorityConsensusRepository",
    "AuthorityConsensusSnapshot",
    "AuthorityConsensusState",
    "AuthorityEnvelopeError",
    "AuthorityKeyProvider",
    "AuthorityMember",
    "AuthorityMembership",
    "AuthorityNetworkEnvelope",
    "AuthorityPrepareMessage",
    "AuthorityPromiseMessage",
    "AuthorityQuorumCertificate",
    "AuthorityRecord",
    "AuthorityRejectedMessage",
    "AuthorityTransport",
    "AuthorityVote",
    "AuthorityVoteCollector",
    "ClusterIdentityMaterial",
    "ClusterPublicIdentity",
    "EncryptedAuthorityStore",
    "NodeInstallationIdentity",
    "OperatorIdentityRepository",
    "SqliteAuthorityConsensusRepository",
    "apply_quorum_certified_payload",
    "authority_bootstrap_position",
    "authority_commit_digest",
    "authority_membership_digest",
    "authority_payload_digest",
    "create_authority_member",
    "create_authority_envelope",
    "create_authority_vote",
    "create_cluster_identity",
    "validate_authority_descriptor",
    "verify_authority_envelope",
    "verify_quorum_certificate",
]
