"""Audio-video generation request, reference, progress, and output contracts.

These types travel three places: the API validates a caller's request into
``VideoGenerationTaskParams``; the master carries them unchanged onto the
``VideoGeneration`` task; and the worker fills in ``local_path`` on each
reference before handing the task to its runner. Generated bytes never ride
these models. The runner writes the finished container under the node's video
output directory and describes it with a ``VideoOutputManifest``; the worker
streams the file to the owning API over the ``OUTPUT_MEDIA`` plane, and the
API keeps it in its video store until it expires.
"""

from __future__ import annotations

import re
from typing import Annotated, Final, Literal, cast, get_args

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from skulk.shared.models.model_cards import (
    VideoCardConfig,
    VideoCompanionKind,
    VideoMode,
    VideoPreprocessorRole,
)
from skulk.utils.pydantic_ext import CamelCaseModel

VideoReferenceKind = Literal["image", "video", "audio"]
"""Media families a request may attach as conditioning input."""

VideoReferenceRole = Literal[
    "first_frame", "last_frame", "keyframe", "reference", "control", "mask", "source"
]
"""How one attachment conditions generation.

``first_frame`` and ``last_frame`` are the keyframe anchors of ``fl2va``;
``reference`` is a numbered subject, clip, or audio reference for ``ref2va``.
``control``, ``mask`` and ``source`` feed the card's ControlNet: a control
video (edges, depth, pose) the render follows, a mask whose white marks what
to regenerate, and the clip behind that mask.
"""

VIDEO_STRUCTURAL_ROLES: Final = frozenset({"control", "mask", "source"})
"""Roles that steer the model through its ControlNet rather than condition it.

They never decide the mode, never count against the card's reference limits,
and never reach the conditioning node: a control clip read as a first frame
would silently become a keyframe.
"""

VideoStage = Literal[
    "queued",
    "encoding",
    "sampling",
    "decoding",
    "muxing",
    "uploading",
]
"""Coarse render phases reported through progress chunks."""

_SIZE_PATTERN = re.compile(r"^([1-9][0-9]{1,4})x([1-9][0-9]{1,4})$")
_SHA256_PATTERN = r"^[0-9a-f]{64}$"
MAX_VIDEO_REFERENCES = 16
MAX_VIDEO_KEYFRAMES = 8
"""Timed keyframes per request; each anchors one frame of the clip."""
"""Upper bound on attachments per request before card limits apply."""
MAX_VIDEO_PROMPT_CHARS = 8000

VIDEO_SAMPLERS: Final[tuple[str, ...]] = (
    "res_multistep",
    "res_multistep_ancestral",
    "euler",
    "euler_ancestral",
    "heun",
    "heunpp2",
    "exp_heun_2_x0",
    "exp_heun_2_x0_sde",
    "dpm_2",
    "dpm_2_ancestral",
    "lms",
    "dpmpp_2s_ancestral",
    "dpmpp_sde",
    "dpmpp_sde_gpu",
    "dpmpp_2m",
    "dpmpp_2m_sde",
    "dpmpp_2m_sde_gpu",
    "dpmpp_2m_sde_heun",
    "dpmpp_2m_sde_heun_gpu",
    "dpmpp_3m_sde",
    "dpmpp_3m_sde_gpu",
    "ddpm",
    "lcm",
    "ipndm",
    "ipndm_v",
    "deis",
    "gradient_estimation",
    "er_sde",
    "seeds_2",
    "seeds_3",
    "sa_solver",
    "sa_solver_pece",
    "ddim",
    "uni_pc",
    "uni_pc_bh2",
)
"""Samplers a video request may name: the pinned ComfyUI's ``KSamplerSelect``
list minus the ones that cannot serve distilled H3 (see
``VIDEO_UNAVAILABLE_SAMPLER_REASONS``). A caller curates further; this is the
engine's truthful set, not a recommendation."""

VIDEO_UNAVAILABLE_SAMPLER_REASONS: Final[dict[str, str]] = {
    "dpm_fast": "chooses its own step count from a sigma range, so render time and the plan cannot be predicted",
    "dpm_adaptive": "chooses its own step count from a sigma range, so render time and the plan cannot be predicted",
    "cfgpp_ud10_ab": "needs a classifier-free guidance branch, which distilled H3 does not have",
}
"""Samplers refused by name, with the reason the refusal gives. Every
``*_cfg_pp`` variant is refused for the CFG reason as well."""

VideoSchedulerName = Literal[
    "simple",
    "normal",
    "sgm_uniform",
    "beta",
    "kl_optimal",
    "linear_quadratic",
    "karras",
    "exponential",
    "ddim_uniform",
]
"""Sigma schedules the pinned ComfyUI's ``BasicScheduler`` offers."""

VideoReferenceFidelity = Literal["match", "max"]
"""How ``ref2va`` sizes reference images: ``match`` the output canvas, or
``max`` (keep them at full resolution; stronger likeness, several times
slower by the node's own account)."""

VideoCodecName = Literal["h264", "av1"]
"""Video codecs the pinned ComfyUI's ``SaveVideo`` writes into MP4."""

MAX_VIDEO_STYLES = 4
"""Style embeddings one request may apply."""

VIDEO_SHIFT_BOUNDS: Final = (0.01, 100.0)
"""The ``MiniMaxH3SigmaShift`` node's accepted range for either shift."""

VIDEO_CONTROL_STRENGTH_MAX: Final = 10.0
"""The ``MiniMaxH3FunControlNetApply`` node's upper bound on strength."""

VideoGuideKind = Literal["pose", "depth", "edges"]
"""What a render derives from an ordinary ``control`` clip to steer by: the
figures' whole-body pose, the scene's depth, or its edges. The ControlNet
union follows each; HED and MLSD have no built-in preprocessor."""

VIDEO_GUIDE_KINDS: Final[tuple[str, ...]] = ("pose", "depth", "edges")
"""Every guide kind, in the order a caller is offered them."""

VIDEO_DEFAULT_GUIDE: Final[VideoGuideKind] = "pose"
"""The guide a ``control`` clip gives when the request names none: the one
ComfyUI's own H3 ControlNet template derives."""

VIDEO_GUIDE_PREPROCESSORS: Final[dict[str, tuple[VideoPreprocessorRole, ...]]] = {
    "pose": (VideoPreprocessorRole.PoseEstimator, VideoPreprocessorRole.PersonDetector),
    "depth": (VideoPreprocessorRole.DepthEstimator,),
    "edges": (),
}
"""The preprocessor weights each guide needs from the card; edges need none."""


def derivable_guides(video: VideoCardConfig, mode: VideoMode) -> tuple[str, ...]:
    """The guide kinds a card can derive for ``mode``, in offer order.

    A guide steers through the card's ControlNet, so a card without one for
    the mode derives none; each kind also needs every preprocessor role it
    names among the card's companions.
    """
    has_controlnet = any(
        companion.kind is VideoCompanionKind.ModelPatch
        and (not companion.modes or mode in companion.modes)
        for companion in video.companions
    )
    if not has_controlnet:
        return ()
    roles = {companion.role for companion in video.companions if companion.role is not None}
    return tuple(
        kind
        for kind in VIDEO_GUIDE_KINDS
        if all(role in roles for role in VIDEO_GUIDE_PREPROCESSORS[kind])
    )

VIDEO_DEFAULT_SAMPLER: Final = "res_multistep"
"""Sampler a render uses when the request names none."""

VIDEO_DEFAULT_SCHEDULER: Final = "simple"
"""Sigma schedule a render uses when the request names none."""

VIDEO_SCHEDULERS: Final[tuple[str, ...]] = get_args(VideoSchedulerName)
"""Every schedule a video request may name, in the engine's order."""

VIDEO_DEFAULT_REFERENCE_FIDELITY: Final = "match"
"""Reference sizing a ``ref2va`` render uses when the request names none."""

VIDEO_REFERENCE_FIDELITIES: Final[tuple[str, ...]] = get_args(VideoReferenceFidelity)
"""Every reference sizing a ``ref2va`` request may name."""

VIDEO_DEFAULT_CODEC: Final = "h264"
"""Codec a render is written with when the request names none."""

VIDEO_CODECS: Final[tuple[str, ...]] = get_args(VideoCodecName)
"""Every codec a video request may name."""


def video_sampler_refusal(name: str) -> str | None:
    """Why ``name`` cannot be used as a video sampler, or ``None`` when it can."""
    if name in VIDEO_UNAVAILABLE_SAMPLER_REASONS:
        return f"sampler {name!r} {VIDEO_UNAVAILABLE_SAMPLER_REASONS[name]}"
    if name.endswith("_cfg_pp"):
        return (
            f"sampler {name!r} needs a classifier-free guidance branch, which "
            "distilled H3 does not have"
        )
    if name not in VIDEO_SAMPLERS:
        return f"sampler {name!r} is not offered by the pinned engine"
    return None
"""Prompt length ceiling; structured H3 prompts run to several thousand chars."""


class VideoReferenceSpec(CamelCaseModel):
    """One conditioning attachment described without its bytes.

    The bytes travel on the reference-media plane keyed by ``slot``; this
    record is what the master replicates and what the worker verifies the
    delivered bytes against before it lets a runner see them.
    """

    model_config = ConfigDict(frozen=True)

    slot: int = Field(ge=0, lt=MAX_VIDEO_REFERENCES)
    """Position in the request's attachment order; the media-plane slot index."""
    kind: VideoReferenceKind
    """Media family of the attachment."""
    role: VideoReferenceRole = "reference"
    """How the attachment conditions generation."""
    media_type: str
    """MIME type the caller supplied, for example ``image/png``."""
    size_bytes: int = Field(ge=1)
    """Exact byte size of the attachment."""
    sha256: str = Field(pattern=_SHA256_PATTERN)
    """Digest of the attachment bytes, verified by every consumer."""
    filename: str | None = Field(default=None, max_length=255)
    """Caller-supplied name, informational only."""
    at_seconds: float | None = Field(default=None, ge=0)
    """Time into the clip a ``keyframe`` anchors; required for that role and
    absent for every other. The engine snaps it to the nearest frame."""
    local_path: str | None = None
    """Worker-local file holding the verified bytes; filled only on the copy a
    worker hands to its runner, never by the API or master."""

    @field_validator("media_type")
    @classmethod
    def _validate_media_type(cls, value: str) -> str:
        if re.fullmatch(r"[a-z]+/[a-z0-9.+-]+", value) is None:
            raise ValueError("media_type must be a lowercase type/subtype")
        return value

    @model_validator(mode="after")
    def _validate_role_kind(self) -> VideoReferenceSpec:
        if (
            self.role in ("first_frame", "last_frame", "keyframe")
            and self.kind != "image"
        ):
            raise ValueError("keyframe roles require an image attachment")
        if (self.role == "keyframe") != (self.at_seconds is not None):
            raise ValueError("a keyframe carries at_seconds and no other role does")
        if self.role in VIDEO_STRUCTURAL_ROLES and self.kind not in ("image", "video"):
            raise ValueError(f"a {self.role} attachment is an image or a video")
        family = self.media_type.split("/", 1)[0]
        if family != self.kind:
            raise ValueError(f"{self.kind} attachment cannot carry {self.media_type}")
        return self


class VideoGenerationTaskParams(BaseModel):
    """Validated parameters for one audio-video generation.

    The public request shape follows the OpenAI ``/v1/videos`` create body
    (``prompt``, ``model``, ``seconds``, ``size``) plus documented extensions
    (``mode``, ``steps``, ``seed``, ``lora``, ``audio``, attachments). The API
    resolves ``mode`` from the attachments before sending, so downstream
    consumers always see an explicit mode. The model is frozen and strict
    because it is replicated verbatim from API to master to worker.
    """

    model_config = ConfigDict(frozen=True, strict=True, extra="forbid")

    prompt: str = Field(min_length=1, max_length=MAX_VIDEO_PROMPT_CHARS)
    """Generation prompt; structured prompts are passed through verbatim."""
    model: str
    """Card identifier of the video model."""
    seconds: int = Field(ge=1, le=120)
    """Requested duration; the card bounds it further and the engine snaps
    the frame count onto the trained grid."""
    mode: VideoMode | None = None
    """Generation mode; ``None`` only before the API resolves it."""
    size: str | None = None
    """Output canvas as ``WIDTHxHEIGHT``; ``None`` lets the engine pick the
    card's trained canvas for the requested aspect ratio."""
    aspect_ratio: str | None = None
    """Advisory ``W:H`` ratio used when ``size`` is omitted."""
    steps: int | None = Field(default=None, ge=1, le=200)
    """Sampling steps; ``None`` defers to the selected companion or the card."""
    seed: int | None = Field(default=None, ge=0)
    """Deterministic seed when supplied."""
    lora: str | None = None
    """Name of a card companion adapter to apply; ``None`` lets the engine
    choose the card's default distillation adapter."""
    lora_strength: float | None = Field(default=None, ge=0.0, le=2.0)
    """Adapter strength override."""
    audio: bool = True
    """Whether the output must carry the model's synchronized audio track."""
    sampler: str | None = None
    """Sampler name; ``None`` keeps the engine default (``res_multistep``)."""
    scheduler: VideoSchedulerName | None = None
    """Sigma schedule; ``None`` keeps the engine default (``simple``)."""
    video_shift: float | None = Field(
        default=None, ge=VIDEO_SHIFT_BOUNDS[0], le=VIDEO_SHIFT_BOUNDS[1]
    )
    """Video sigma shift; ``None`` takes the adapter's, else the card's."""
    audio_shift: float | None = Field(
        default=None, ge=VIDEO_SHIFT_BOUNDS[0], le=VIDEO_SHIFT_BOUNDS[1]
    )
    """Audio sigma shift; ``None`` takes the adapter's, else the card's."""
    reference_fidelity: VideoReferenceFidelity | None = None
    """``ref2va`` reference-image sizing; ``None`` keeps ``match``."""
    styles: tuple[str, ...] = Field(default=(), max_length=MAX_VIDEO_STYLES)
    """Card style embeddings to apply, by companion name, in order."""
    codec: VideoCodecName | None = None
    """Output video codec in the MP4 container; ``None`` keeps ``h264``."""
    control_strength: float | None = Field(
        default=None, ge=0.0, le=VIDEO_CONTROL_STRENGTH_MAX
    )
    """ControlNet strength; ``None`` takes the card companion's."""
    control_start: float = Field(default=0.0, ge=0.0, le=1.0)
    """Fraction of the schedule at which the ControlNet starts to steer."""
    control_end: float = Field(default=1.0, ge=0.0, le=1.0)
    """Fraction of the schedule at which it stops; above ``control_start``."""
    control_kind: VideoGuideKind | None = None
    """What to derive from the ``control`` clip; ``None`` derives the default
    guide (pose). Meaningful only with a ``control`` attachment."""
    references: tuple[VideoReferenceSpec, ...] = ()
    """Conditioning attachments in slot order."""
    total_input_chunks: int = Field(default=0, ge=0)
    """Number of reference-media frames the worker must verify before dispatch."""
    reference_bytes: int = Field(default=0, ge=0)
    """Total attachment bytes, for admission accounting."""

    @field_validator("references", mode="before")
    @classmethod
    def _coerce_references(cls, value: object) -> object:
        if isinstance(value, list):
            return tuple(cast("list[object]", value))
        return value

    @field_validator("styles", mode="before")
    @classmethod
    def _coerce_styles(cls, value: object) -> object:
        if isinstance(value, list):
            return tuple(cast("list[object]", value))
        return value

    @field_validator("styles")
    @classmethod
    def _validate_styles(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        if len(set(value)) != len(value):
            raise ValueError("a style may be applied once")
        if any(not name or name != name.strip() for name in value):
            raise ValueError("style names must be non-empty and unpadded")
        return value

    @field_validator("sampler")
    @classmethod
    def _validate_sampler(cls, value: str | None) -> str | None:
        if value is not None and (refusal := video_sampler_refusal(value)):
            raise ValueError(refusal)
        return value

    @field_validator("size")
    @classmethod
    def _validate_size(cls, value: str | None) -> str | None:
        if value is not None and _SIZE_PATTERN.fullmatch(value) is None:
            raise ValueError("size must be WIDTHxHEIGHT")
        return value

    @field_validator("aspect_ratio")
    @classmethod
    def _validate_aspect_ratio(cls, value: str | None) -> str | None:
        if (
            value is not None
            and re.fullmatch(r"[1-9][0-9]*:[1-9][0-9]*", value) is None
        ):
            raise ValueError("aspect_ratio must be W:H")
        return value

    @field_validator("mode", mode="before")
    @classmethod
    def _validate_mode(cls, value: str | VideoMode | None) -> VideoMode | None:
        if value is None or isinstance(value, VideoMode):
            return value
        return VideoMode(value)

    @model_validator(mode="after")
    def _validate_references(self) -> VideoGenerationTaskParams:
        slots = [item.slot for item in self.references]
        if slots != list(range(len(slots))):
            raise ValueError("reference slots must be contiguous from zero")
        roles = [item.role for item in self.references]
        for role in ("first_frame", "last_frame"):
            if roles.count(role) > 1:
                raise ValueError(f"at most one {role} attachment is allowed")
        keyframes = [item for item in self.references if item.role == "keyframe"]
        if len(keyframes) > MAX_VIDEO_KEYFRAMES:
            raise ValueError(f"at most {MAX_VIDEO_KEYFRAMES} keyframes are allowed")
        times = [item.at_seconds for item in keyframes]
        if len(set(times)) != len(times):
            raise ValueError("keyframes must anchor distinct times")
        if any(time is not None and time > self.seconds for time in times):
            raise ValueError("a keyframe cannot lie past the end of the clip")
        if self.references and self.reference_bytes != sum(
            item.size_bytes for item in self.references
        ):
            raise ValueError("reference_bytes must equal the attachment total")
        if not self.references and (self.reference_bytes or self.total_input_chunks):
            raise ValueError("reference accounting requires attachments")
        if (
            self.reference_fidelity is not None
            and self.implied_mode() is not VideoMode.ReferenceToAudioVideo
        ):
            raise ValueError("reference_fidelity applies to ref2va only")
        for role in VIDEO_STRUCTURAL_ROLES:
            if roles.count(role) > 1:
                raise ValueError(f"at most one {role} attachment is allowed")
        if "source" in roles and "mask" not in roles:
            raise ValueError("a source clip is read only behind a mask")
        steered = "control" in roles or "mask" in roles
        if not steered and (
            self.control_strength is not None
            or self.control_start != 0.0
            or self.control_end != 1.0
        ):
            raise ValueError("control settings need a control or mask attachment")
        if self.control_start >= self.control_end:
            raise ValueError("control_start must come before control_end")
        if self.control_kind is not None and "control" not in roles:
            raise ValueError("control_kind names what to derive from a control clip")
        if self.references and self.total_input_chunks < len(self.references):
            # Every attachment occupies at least one media frame; a smaller
            # count would let the worker's ingress gate treat the task as
            # having no attachments and dispatch it without their bytes.
            raise ValueError("total_input_chunks must cover every attachment")
        return self

    @property
    def width_height(self) -> tuple[int, int] | None:
        """Return the explicit canvas as integers when ``size`` is set."""
        if self.size is None:
            return None
        match = _SIZE_PATTERN.fullmatch(self.size)
        assert match is not None
        return int(match.group(1)), int(match.group(2))

    def implied_mode(self) -> VideoMode:
        """Derive the generation mode from the attachments."""
        if self.mode is not None:
            return self.mode
        roles = {item.role for item in self.references}
        if "reference" in roles:
            return VideoMode.ReferenceToAudioVideo
        if roles & {"first_frame", "last_frame", "keyframe"}:
            return VideoMode.FramesToAudioVideo
        return VideoMode.TextToAudioVideo


class VideoOutputManifest(CamelCaseModel):
    """Description of one finished container, without its bytes.

    The runner produces it beside the file; the worker verifies the file
    against it before streaming; the API verifies the received bytes against
    it before the job completes.
    """

    model_config = ConfigDict(frozen=True)

    sha256: str = Field(pattern=_SHA256_PATTERN)
    """Digest of the container bytes."""
    size_bytes: int = Field(ge=1)
    """Exact container size."""
    content_type: Literal["video/mp4"] = "video/mp4"
    """Container MIME type. The codecs inside are the engine's (the MiniMax H3
    engines mux H.264 video with AAC audio; the test engine muxes MJPEG frames
    with 16-bit PCM), so consumers read them from the file."""
    width: int = Field(ge=1)
    """Frame width in pixels."""
    height: int = Field(ge=1)
    """Frame height in pixels."""
    frame_count: int = Field(ge=1)
    """Number of video frames."""
    fps: int = Field(ge=1)
    """Frames per second."""
    seconds: float = Field(gt=0)
    """Duration in seconds as muxed."""
    audio_sample_rate: int | None = Field(default=None, ge=1)
    """Audio sample rate when a track is present."""
    audio_channels: int | None = Field(default=None, ge=1)
    """Audio channel count when a track is present."""
    thumbnail_sha256: str | None = Field(default=None, pattern=_SHA256_PATTERN)
    """Digest of the optional JPEG thumbnail shipped after the container."""
    thumbnail_size_bytes: int | None = Field(default=None, ge=1)
    """Size of the optional thumbnail."""

    @model_validator(mode="after")
    def _validate_thumbnail(self) -> VideoOutputManifest:
        if (self.thumbnail_sha256 is None) != (self.thumbnail_size_bytes is None):
            raise ValueError("thumbnail digest and size must be declared together")
        if (self.audio_sample_rate is None) != (self.audio_channels is None):
            raise ValueError("audio sample rate and channels must be declared together")
        return self


class VideoEngineSettings(CamelCaseModel):
    """What a render actually ran with, after request, adapter and card.

    Recorded so a take says what produced it: a request may leave any of
    these unset and inherit them, and a later card or adapter change must not
    rewrite the history of an earlier take.
    """

    model_config = ConfigDict(frozen=True)

    sampler: str
    """Sampler that integrated the render (a `KSamplerSelect` name)."""
    scheduler: str
    """Schedule that placed its noise levels (a `BasicScheduler` name)."""
    steps: int = Field(ge=1)
    """Sampling steps the schedule ran."""
    seed: int | None = Field(default=None, ge=0)
    """The noise seed the render drew from, resolved when the request gave none."""
    video_shift: float | None = None
    """Video sigma shift applied; ``None`` leaves the loader default."""
    audio_shift: float | None = None
    """Audio sigma shift applied; ``None`` leaves the loader default."""
    adapter: str | None = None
    """Adapter companion name, when one was applied."""
    adapter_strength: float | None = None
    """Strength the adapter was applied at; ``None`` without an adapter."""
    width: int = Field(ge=1)
    """Output canvas width in pixels."""
    height: int = Field(ge=1)
    """Output canvas height in pixels."""
    frame_count: int = Field(ge=1)
    """Frames rendered, on the card's frame grid."""
    reference_fidelity: str | None = None
    """``match`` or ``max`` for ``ref2va``; ``None`` for other modes."""
    styles: tuple[str, ...] = ()
    """Style embeddings bound into the prompt, in request order."""
    codec: str
    """Video codec of the saved container (`h264` or `av1`)."""
    control_inputs: tuple[str, ...] = ()
    """The ControlNet inputs the render used (``control``, ``mask``, ``source``)."""
    control_strength: float | None = None
    """ControlNet strength applied; ``None`` when no ControlNet ran."""
    control_start: float | None = None
    """Fraction of the schedule the ControlNet started at, when it ran."""
    control_end: float | None = None
    """Fraction of the schedule the ControlNet stopped at, when it ran."""
    control_kind: str | None = None
    """The guide derived from the control clip; ``None`` without one."""

    @field_validator("styles", "control_inputs", mode="before")
    @classmethod
    def _coerce_styles(cls, value: object) -> object:
        # The job registry persists this record as JSON and reloads it in
        # strict Python mode, where the tuple comes back as a list; refusing
        # it would drop the finished job on restart and orphan its clip.
        if isinstance(value, list):
            return tuple(cast("list[object]", value))
        return value


class VideoGenerationStats(CamelCaseModel):
    """Runner-reported timing for one render."""

    model_config = ConfigDict(frozen=True)

    steps: int = Field(ge=0)
    """Sampling steps actually executed."""
    seconds_per_step: float = Field(ge=0)
    """Mean wall time per sampling step."""
    total_generation_time: float = Field(ge=0)
    """Wall time from dispatch to a finished container."""
    peak_memory_bytes: int | None = Field(default=None, ge=0)
    """Peak accelerator memory observed by the engine when it reports one."""
    engine: VideoEngineSettings | None = None
    """The engine settings the render resolved and ran with."""


VideoJobStatus = Literal["queued", "in_progress", "completed", "failed", "cancelled"]
"""Job states exposed by the video job API (OpenAI vocabulary plus cancelled)."""

VIDEO_OUTPUT_FILENAME: Annotated[str, "runner output container name"] = "output.mp4"
VIDEO_THUMBNAIL_FILENAME: Annotated[str, "runner thumbnail name"] = "thumbnail.jpg"
