"""Audio-video generation request, reference, progress, and output contracts.

These types travel three places: the API validates a caller's request into
``VideoGenerationTaskParams``; the master carries them unchanged onto the
``VideoGeneration`` task; and the worker fills in ``local_path`` on each
reference before handing the task to its runner. Generated bytes never ride
these models. The runner writes the finished container under the node's video
output directory and describes it with a ``VideoOutputManifest``; the worker
streams the file to the owning API over the ``OUTPUT_MEDIA`` plane, and the
API keeps it in its video store until it expires.
"""

from __future__ import annotations

import re
from typing import Annotated, Literal, cast

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from skulk.shared.models.model_cards import VideoMode
from skulk.utils.pydantic_ext import CamelCaseModel

VideoReferenceKind = Literal["image", "video", "audio"]
"""Media families a request may attach as conditioning input."""

VideoReferenceRole = Literal["first_frame", "last_frame", "reference"]
"""How one attachment conditions generation.

``first_frame`` and ``last_frame`` are the keyframe anchors of ``fl2va``;
``reference`` is a numbered subject, clip, or audio reference for ``ref2va``.
"""

VideoStage = Literal[
    "queued",
    "encoding",
    "sampling",
    "decoding",
    "muxing",
    "uploading",
]
"""Coarse render phases reported through progress chunks."""

_SIZE_PATTERN = re.compile(r"^([1-9][0-9]{1,4})x([1-9][0-9]{1,4})$")
_SHA256_PATTERN = r"^[0-9a-f]{64}$"
MAX_VIDEO_REFERENCES = 16
"""Upper bound on attachments per request before card limits apply."""
MAX_VIDEO_PROMPT_CHARS = 8000
"""Prompt length ceiling; structured H3 prompts run to several thousand chars."""


class VideoReferenceSpec(CamelCaseModel):
    """One conditioning attachment described without its bytes.

    The bytes travel on the reference-media plane keyed by ``slot``; this
    record is what the master replicates and what the worker verifies the
    delivered bytes against before it lets a runner see them.
    """

    model_config = ConfigDict(frozen=True)

    slot: int = Field(ge=0, lt=MAX_VIDEO_REFERENCES)
    """Position in the request's attachment order; the media-plane slot index."""
    kind: VideoReferenceKind
    """Media family of the attachment."""
    role: VideoReferenceRole = "reference"
    """How the attachment conditions generation."""
    media_type: str
    """MIME type the caller supplied, for example ``image/png``."""
    size_bytes: int = Field(ge=1)
    """Exact byte size of the attachment."""
    sha256: str = Field(pattern=_SHA256_PATTERN)
    """Digest of the attachment bytes, verified by every consumer."""
    filename: str | None = Field(default=None, max_length=255)
    """Caller-supplied name, informational only."""
    local_path: str | None = None
    """Worker-local file holding the verified bytes; filled only on the copy a
    worker hands to its runner, never by the API or master."""

    @field_validator("media_type")
    @classmethod
    def _validate_media_type(cls, value: str) -> str:
        if re.fullmatch(r"[a-z]+/[a-z0-9.+-]+", value) is None:
            raise ValueError("media_type must be a lowercase type/subtype")
        return value

    @model_validator(mode="after")
    def _validate_role_kind(self) -> VideoReferenceSpec:
        if self.role in ("first_frame", "last_frame") and self.kind != "image":
            raise ValueError("keyframe roles require an image attachment")
        family = self.media_type.split("/", 1)[0]
        if family != self.kind:
            raise ValueError(f"{self.kind} attachment cannot carry {self.media_type}")
        return self


class VideoGenerationTaskParams(BaseModel):
    """Validated parameters for one audio-video generation.

    The public request shape follows the OpenAI ``/v1/videos`` create body
    (``prompt``, ``model``, ``seconds``, ``size``) plus documented extensions
    (``mode``, ``steps``, ``seed``, ``lora``, ``audio``, attachments). The API
    resolves ``mode`` from the attachments before sending, so downstream
    consumers always see an explicit mode. The model is frozen and strict
    because it is replicated verbatim from API to master to worker.
    """

    model_config = ConfigDict(frozen=True, strict=True, extra="forbid")

    prompt: str = Field(min_length=1, max_length=MAX_VIDEO_PROMPT_CHARS)
    """Generation prompt; structured prompts are passed through verbatim."""
    model: str
    """Card identifier of the video model."""
    seconds: int = Field(ge=1, le=120)
    """Requested duration; the card bounds it further and the engine snaps
    the frame count onto the trained grid."""
    mode: VideoMode | None = None
    """Generation mode; ``None`` only before the API resolves it."""
    size: str | None = None
    """Output canvas as ``WIDTHxHEIGHT``; ``None`` lets the engine pick the
    card's trained canvas for the requested aspect ratio."""
    aspect_ratio: str | None = None
    """Advisory ``W:H`` ratio used when ``size`` is omitted."""
    steps: int | None = Field(default=None, ge=1, le=200)
    """Sampling steps; ``None`` defers to the selected companion or the card."""
    seed: int | None = Field(default=None, ge=0)
    """Deterministic seed when supplied."""
    lora: str | None = None
    """Name of a card companion adapter to apply; ``None`` lets the engine
    choose the card's default distillation adapter."""
    lora_strength: float | None = Field(default=None, ge=0.0, le=2.0)
    """Adapter strength override."""
    audio: bool = True
    """Whether the output must carry the model's synchronized audio track."""
    references: tuple[VideoReferenceSpec, ...] = ()
    """Conditioning attachments in slot order."""
    total_input_chunks: int = Field(default=0, ge=0)
    """Number of reference-media frames the worker must verify before dispatch."""
    reference_bytes: int = Field(default=0, ge=0)
    """Total attachment bytes, for admission accounting."""

    @field_validator("references", mode="before")
    @classmethod
    def _coerce_references(cls, value: object) -> object:
        if isinstance(value, list):
            return tuple(cast("list[object]", value))
        return value

    @field_validator("size")
    @classmethod
    def _validate_size(cls, value: str | None) -> str | None:
        if value is not None and _SIZE_PATTERN.fullmatch(value) is None:
            raise ValueError("size must be WIDTHxHEIGHT")
        return value

    @field_validator("aspect_ratio")
    @classmethod
    def _validate_aspect_ratio(cls, value: str | None) -> str | None:
        if value is not None and re.fullmatch(r"[1-9][0-9]*:[1-9][0-9]*", value) is None:
            raise ValueError("aspect_ratio must be W:H")
        return value

    @field_validator("mode", mode="before")
    @classmethod
    def _validate_mode(cls, value: str | VideoMode | None) -> VideoMode | None:
        if value is None or isinstance(value, VideoMode):
            return value
        return VideoMode(value)

    @model_validator(mode="after")
    def _validate_references(self) -> VideoGenerationTaskParams:
        slots = [item.slot for item in self.references]
        if slots != list(range(len(slots))):
            raise ValueError("reference slots must be contiguous from zero")
        roles = [item.role for item in self.references]
        for role in ("first_frame", "last_frame"):
            if roles.count(role) > 1:
                raise ValueError(f"at most one {role} attachment is allowed")
        if self.references and self.reference_bytes != sum(
            item.size_bytes for item in self.references
        ):
            raise ValueError("reference_bytes must equal the attachment total")
        if not self.references and (self.reference_bytes or self.total_input_chunks):
            raise ValueError("reference accounting requires attachments")
        if self.references and self.total_input_chunks < len(self.references):
            # Every attachment occupies at least one media frame; a smaller
            # count would let the worker's ingress gate treat the task as
            # having no attachments and dispatch it without their bytes.
            raise ValueError("total_input_chunks must cover every attachment")
        return self

    @property
    def width_height(self) -> tuple[int, int] | None:
        """Return the explicit canvas as integers when ``size`` is set."""
        if self.size is None:
            return None
        match = _SIZE_PATTERN.fullmatch(self.size)
        assert match is not None
        return int(match.group(1)), int(match.group(2))

    def implied_mode(self) -> VideoMode:
        """Derive the generation mode from the attachments."""
        if self.mode is not None:
            return self.mode
        roles = {item.role for item in self.references}
        if "reference" in roles:
            return VideoMode.ReferenceToAudioVideo
        if roles & {"first_frame", "last_frame"}:
            return VideoMode.FramesToAudioVideo
        return VideoMode.TextToAudioVideo


class VideoOutputManifest(CamelCaseModel):
    """Description of one finished container, without its bytes.

    The runner produces it beside the file; the worker verifies the file
    against it before streaming; the API verifies the received bytes against
    it before the job completes.
    """

    model_config = ConfigDict(frozen=True)

    sha256: str = Field(pattern=_SHA256_PATTERN)
    """Digest of the container bytes."""
    size_bytes: int = Field(ge=1)
    """Exact container size."""
    content_type: Literal["video/mp4"] = "video/mp4"
    """Container MIME type; MP4 with H.264 video and AAC audio in v1."""
    width: int = Field(ge=1)
    """Frame width in pixels."""
    height: int = Field(ge=1)
    """Frame height in pixels."""
    frame_count: int = Field(ge=1)
    """Number of video frames."""
    fps: int = Field(ge=1)
    """Frames per second."""
    seconds: float = Field(gt=0)
    """Duration in seconds as muxed."""
    audio_sample_rate: int | None = Field(default=None, ge=1)
    """Audio sample rate when a track is present."""
    audio_channels: int | None = Field(default=None, ge=1)
    """Audio channel count when a track is present."""
    thumbnail_sha256: str | None = Field(default=None, pattern=_SHA256_PATTERN)
    """Digest of the optional JPEG thumbnail shipped after the container."""
    thumbnail_size_bytes: int | None = Field(default=None, ge=1)
    """Size of the optional thumbnail."""

    @model_validator(mode="after")
    def _validate_thumbnail(self) -> VideoOutputManifest:
        if (self.thumbnail_sha256 is None) != (self.thumbnail_size_bytes is None):
            raise ValueError("thumbnail digest and size must be declared together")
        if (self.audio_sample_rate is None) != (self.audio_channels is None):
            raise ValueError("audio sample rate and channels must be declared together")
        return self


class VideoGenerationStats(CamelCaseModel):
    """Runner-reported timing for one render."""

    model_config = ConfigDict(frozen=True)

    steps: int = Field(ge=0)
    """Sampling steps actually executed."""
    seconds_per_step: float = Field(ge=0)
    """Mean wall time per sampling step."""
    total_generation_time: float = Field(ge=0)
    """Wall time from dispatch to a finished container."""
    peak_memory_bytes: int | None = Field(default=None, ge=0)
    """Peak accelerator memory observed by the engine when it reports one."""


VideoJobStatus = Literal["queued", "in_progress", "completed", "failed", "cancelled"]
"""Job states exposed by the video job API (OpenAI vocabulary plus cancelled)."""

VIDEO_OUTPUT_FILENAME: Annotated[str, "runner output container name"] = "output.mp4"
VIDEO_THUMBNAIL_FILENAME: Annotated[str, "runner thumbnail name"] = "thumbnail.jpg"
