import { useEffect } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { useAppDispatch } from '../store/hooks';
import { uiActions } from '../store/slices/uiSlice';
import { Surface } from './common/Surfaces';
import { NetworkMesh } from './common/NetworkMesh';
import { SceneBackdrop } from './common/SceneBackdrop';
import { ShootingStars } from './common/ShootingStars';
import { ObservabilityPanel } from './observability/ObservabilityPanel';
import { CapabilityPanel } from './capabilities/CapabilityPanel';
import { MobileMenuSheet } from './layout/MobileMenuSheet';
import { TelemetryConsentModal } from './layout/TelemetryConsentModal';
import { ModelSearchModal } from './pages/ModelSearchModal';
import { RuntimeReleasePanel } from './pages/RuntimeReleasePanel';
import { PlacementManager } from './cluster/PlacementManager';
import { HfModelDossier } from './models/HfModelDossier';
import { BurstChip } from './models/BurstChip';
import { QuantBadge } from './models/quantBadge';
import { ClusterWarnings } from './status/ClusterWarnings';
import { CapabilitySatellite, CapabilityOverflow } from './topology/CapabilitySatellite';
import { CapabilityFlyout } from './topology/CapabilityFlyout';
import { TopologyNodeActions } from './topology/TopologyNodeActions';
import { TraceWaterfall } from './observability/TraceWaterfall';
import type { CapabilityNodeSummary } from '../types/capabilityNodes';
const capability: CapabilityNodeSummary = { pluginId: 'example', nodeId: 'video', bundleId: 'example.video', title: 'Video Studio', version: '1.0.0', status: 'ready', ownerAvailable: true, surfaces: [], actions: [], operationsActive: 0, observedAt: '2026-09-18T12:00:00Z' };
const meta = { title: 'Inventory/Details and overlays', parameters: { layout: 'fullscreen' }, decorators: [(Story) => <div style={{ minHeight: '100vh', padding: 24 }}><Story /></div>] } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;
function Panel({ capabilityPanel = false }: { capabilityPanel?: boolean }) {
  const dispatch = useAppDispatch();
  useEffect(() => { if (capabilityPanel) dispatch(uiActions.openCapabilityPanel({ target: { hostNodeId: 'example', key: 'example/video' } })); else dispatch(uiActions.openObservability({})); }, [dispatch, capabilityPanel]);
  return capabilityPanel ? <CapabilityPanel /> : <ObservabilityPanel />;
}
export const Observability: Story = { render: () => <Panel /> };
export const Capabilities: Story = { render: () => <Panel capabilityPanel /> };
export const Background: Story = { render: () => <><NetworkMesh /><SceneBackdrop /><ShootingStars /><Surface style={{ position: 'relative' }}>Background layers use the active palette.</Surface></> };
export const MobileMenu: Story = { render: () => <div style={{ position: 'relative', height: 60 }}><MobileMenuSheet open activeRoute="cluster" onNavigate={() => {}} onOpenSettings={() => {}} onClose={() => {}} /></div> };
export const Telemetry: Story = { render: () => <TelemetryConsentModal /> };
export const FindModelsEmpty: Story = { render: () => <ModelSearchModal open onClose={() => {}} existingModelIds={new Set()} onDownloadStarted={() => {}} /> };
export const Placement: Story = { render: () => <PlacementManager open modelId="example/model" modelSizeMb={4000} topology={{ nodes: {}, edges: [] }} onClose={() => {}} onLaunch={() => {}} /> };
export const ReleaseUnavailable: Story = { render: () => <RuntimeReleasePanel runtime={{ plugin_id: 'example', selected_digest: null, selection_revision: 1, enabled: false, stale: true, error_code: null, operation_id: null, operation_state: null, service: null }} /> };
export const ModelDetails: Story = { render: () => <><HfModelDossier model={{ id: 'example/model', author: 'example', downloads: 100, likes: 12, last_modified: '2026-09-18', tags: ['text-generation'] }} author="example" /><BurstChip info={{ reason: 'engine', format: 'GGUF' }} /><QuantBadge>Q4_K_M</QuantBadge></> };
export const WarningsEmpty: Story = { render: () => <ClusterWarnings topology={null} /> };
export const Satellites: Story = { render: () => <svg width="240" height="100"><CapabilitySatellite summary={capability} x={40} y={40} onSelect={() => {}} /><CapabilityOverflow count={3} x={110} y={40} onSelect={() => {}} /></svg> };
export const Flyout: Story = { render: () => <div style={{ position: 'relative', height: 600 }}><CapabilityFlyout summaries={[capability]} selectedKey="example/video" onSelectKey={() => {}} hostNodeId="example" hostName="Example host" localNodeId="example" anchor={{ x: 100, y: 60 }} canvasWidth={800} canvasHeight={600} onClose={() => {}} onOpenPanel={() => {}} /></div> };
export const NodeActions: Story = { render: () => <TopologyNodeActions infoContent="Example node" onRestart={() => {}} onInspect={() => {}} /> };
export const Waterfall: Story = { render: () => <TraceWaterfall events={[{ id: 'prefill', laneKey: 'example', laneLabel: 'Example worker', startUs: 0, durationUs: 12000, category: 'compute', name: 'Prefill' }, { id: 'decode', laneKey: 'example', laneLabel: 'Example worker', startUs: 13000, durationUs: 24000, category: 'compute', name: 'Decode' }]} /> };
