from __future__ import annotations

import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WEBSITE_DIR = REPO_ROOT / "website"
DASHBOARD_DIR = REPO_ROOT / "dashboard-react"


def run(cmd: list[str], cwd: Path | None = None) -> None:
    """Run a subprocess command, raising on non-zero exit."""
    subprocess.run(cmd, cwd=cwd or REPO_ROOT, check=True)


def main() -> None:
    # 1. Generate the OpenAPI schema JSON into docs/generated/.
    #    docusaurus-plugin-openapi-docs reads this at build time.
    run(["uv", "run", "python", "scripts/export_openapi.py"])

    # 2. Generate the TypeDoc HTML reference into website/static/typedoc/.
    #    Docusaurus serves static/ at the root, so the output is reachable at
    #    /typedoc/ without any further integration.
    run(["npm", "run", "docs:typedoc"], cwd=DASHBOARD_DIR)

    # 3. Generate per-endpoint MDX from the OpenAPI spec.
    #    The plugin writes into website/docs/api/ which the autogenerated
    #    sidebar then picks up automatically.
    run(["npm", "run", "gen-api-docs"], cwd=WEBSITE_DIR)

    # 4. Build the Docusaurus site into website/build/.
    run(["npm", "run", "build"], cwd=WEBSITE_DIR)


if __name__ == "__main__":
    main()
