#!/bin/zsh
# rename_to_skulk.sh — the exo -> skulk identity migration, as one reviewable
# mechanical transformation. Run once from the repo root on a clean tree.
#
# What it does (in order):
#   1. git mv the Python package, the Rust bindings crate, and its stub file.
#   2. Targeted textual replacements across tracked text files. Patterns are
#      deliberately NARROW (import forms, path forms, env-var prefix, wire
#      field names, storage keys) — never a blanket exo->skulk — so upstream
#      attribution ("forked from exo", exo-explore URLs) survives untouched.
#   3. Build-system metadata (pyproject, Cargo workspace, maturin, nix).
#   4. A leftover report: every remaining whole-word "exo" for manual triage.
#
# Deliberately NOT touched here (manual follow-ups in the same branch):
#   - the EXO_* -> SKULK_* runtime compat shim (added to constants.py by hand)
#   - the ~/.exo/staging legacy-path fallback (store config, by hand)
#   - dashboard localStorage one-time migration (by hand)
#   - Tier-A prose (identity lines, docstrings, the wrong-repo screenshot URL)
#   - uv.lock / Cargo.lock — regenerated by `uv sync` / cargo, never sed'd
set -euo pipefail

[ -f pyproject.toml ] || { echo "run from the repo root"; exit 1; }
[ -z "$(git status --porcelain)" ] || { echo "tree not clean"; exit 1; }

echo "== Phase 1: moves =="
git mv src/exo src/skulk
git mv rust/exo_pyo3_bindings rust/skulk_pyo3_bindings
git mv rust/skulk_pyo3_bindings/exo_pyo3_bindings.pyi \
       rust/skulk_pyo3_bindings/skulk_pyo3_bindings.pyi

echo "== Phase 2: textual replacements =="
# Tracked text files only; lockfiles and binary-ish assets excluded.
FILES=$(git ls-files | grep -vE '\.(lock|png|jpg|jpeg|gif|ico|woff2?|safetensors)$|^uv\.lock$|^Cargo\.lock$|package-lock\.json$')

replace() { # replace <perl-substitution>
  echo "  $1"
  echo "$FILES" | tr '\n' '\0' | xargs -0 perl -pi -e "$1"
}

# Order matters: the bindings crate contains "exo" and must go first so the
# narrower exo.* patterns never half-match it.
replace 's/exo_pyo3_bindings/skulk_pyo3_bindings/g'
# Python import forms (source, tests, patch-target strings).
replace 's/\bfrom exo\./from skulk./g'
replace 's/\bfrom exo import\b/from skulk import/g'
replace 's/\bimport exo\./import skulk./g'
replace 's/\bimport exo\b/import skulk/g'
# Quoted dotted-module strings: mocker.patch("exo.x"), entry points
# ("exo.main:main"), loguru module filters. ("exo.yaml" in prose becomes
# "skulk.yaml", which is the correct current filename anyway.)
replace 's/"exo\./"skulk./g'
replace "s/'exo\\./'skulk./g"
# Path forms in docs, comments, configs.
replace 's{src/exo/}{src/skulk/}g'
replace 's{src/exo\b}{src/skulk}g'
# Env-var prefix. The startup shim (manual follow-up) keeps EXO_* honored.
replace 's/\bEXO_/SKULK_/g'
# Wire/state field + dashboard storage keys.
replace 's/\bexo_version\b/skulk_version/g'
replace 's/\bexo_commit\b/skulk_commit/g'
replace 's/\bexoVersion\b/skulkVersion/g'
replace 's/\bexoCommit\b/skulkCommit/g'
replace 's/exo-favorite-models/skulk-favorite-models/g'
replace 's/exo-recent-models/skulk-recent-models/g'

echo "== Phase 3: build metadata =="
perl -pi -e 's/^name = "exo"$/name = "skulk"/' pyproject.toml
# Drop the deprecated `exo` console alias — final means final.
perl -ni -e 'print unless /^exo = "skulk\.main:main"/' pyproject.toml

echo "== Phase 4: leftover report (manual triage) =="
git grep -nwiI "exo" -- ':!*.lock' ':!uv.lock' ':!Cargo.lock' \
  | grep -vE 'exo-explore|forked from \[?exo|skulk_pyo3' || true
echo "== done — review the report above, then run the manual follow-ups =="
