import { chromium } from 'playwright';
const b = await chromium.launch({ headless: true });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto('http://localhost:3000', { waitUntil: 'networkidle' });
const notNow = p.locator('text=Not now');
if (await notNow.count()) await notNow.click();
await p.evaluate(() => localStorage.setItem('skulk-theme', 'dark'));
await p.reload({ waitUntil: 'networkidle' });
await p.waitForTimeout(1500);
await p.locator('text=Model Store').first().click();
await p.waitForTimeout(800);
await p.screenshot({ path: process.env.OUT + '/scene-store.png' });
await p.locator('text=Find Models').first().click();
await p.waitForTimeout(1200);
await p.screenshot({ path: process.env.OUT + '/scene-modal.png' });
await p.keyboard.press('Escape');
await p.locator('text=Chat').first().click();
await p.waitForTimeout(800);
await p.screenshot({ path: process.env.OUT + '/scene-chat.png' });
await b.close();
console.log('done');
