// Copyright 2025 Foxlight Foundation

import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";
import type { PluginOptions as OpenApiPluginOptions } from "docusaurus-plugin-openapi-docs";

const config: Config = {
  title: "Skulk Developer Docs",
  tagline: "Distributed AI inference, edge-to-edge",
  favicon: "img/skulk-logo.svg",

  url: "https://foxlight-foundation.github.io",
  baseUrl: "/Skulk/",

  organizationName: "foxlight-foundation",
  projectName: "Skulk",

  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  // Use Rspack instead of webpack.  The OpenAPI theme's CJS modules have
  // bare `exports.default = ...` that webpack mishandles (placing them
  // outside module wrappers where `exports` is undefined).  Rspack handles
  // CJS/ESM interop correctly and doesn't need any polyfill workarounds.
  future: {
    experimental_faster: true,
    v4: {
      removeLegacyPostBuildHeadAttribute: true,
    },
  },

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars.ts",
          // Serve docs at the site root (/Skulk/) instead of /Skulk/docs/
          // so URLs match the README (e.g. /Skulk/architecture/).
          routeBasePath: "/",
          // Required by docusaurus-plugin-openapi-docs so API pages render
          // with the interactive request/response UI rather than plain MDX.
          docItemComponent: "@theme/ApiItem",
          editUrl:
            "https://github.com/Foxlight-Foundation/Skulk/edit/main/website/",
        },
        blog: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "openapi",
        docsPluginId: "classic",
        config: {
          skulk: {
            // Path is relative to this config file (website/).
            // The JSON is generated by scripts/export_openapi.py before the
            // Docusaurus build runs.
            specPath: "../docs/generated/openapi.json",
            // Generated MDX files land inside the docs tree so the sidebar
            // can discover them automatically.
            outputDir: "docs/api",
            sidebarOptions: {
              groupPathsBy: "tag",
              categoryLinkSource: "tag",
            },
            showSchemas: true,
          } satisfies OpenApiPluginOptions["config"][string],
        },
      } satisfies { id: string; docsPluginId: string; config: OpenApiPluginOptions["config"] },
    ],
  ],

  themes: ["docusaurus-theme-openapi-docs"],

  themeConfig: {
    navbar: {
      title: "Skulk",
      logo: {
        alt: "Skulk Logo",
        src: "img/skulk-logo.svg",
      },
      items: [
        {
          type: "docSidebar",
          sidebarId: "guidesSidebar",
          position: "left",
          label: "Guides",
        },
        {
          type: "docSidebar",
          sidebarId: "apiSidebar",
          position: "left",
          label: "API Reference",
        },
        {
          // TypeDoc HTML is served from website/static/typedoc/ at /typedoc/.
          // Uses the full URL so Docusaurus doesn't treat it as an internal
          // link and fail the broken-link check (static files are invisible
          // to the link checker).
          href: "https://foxlight-foundation.github.io/Skulk/typedoc/",
          label: "TypeScript API",
          position: "left",
        },
        {
          href: "https://github.com/Foxlight-Foundation/Skulk",
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Guides",
          items: [
            { label: "API Guide", to: "/api-guide" },
            { label: "Architecture", to: "/architecture" },
            { label: "Model Store", to: "/model-store" },
            { label: "KV Cache Backends", to: "/kv-cache-backends" },
          ],
        },
        {
          title: "Reference",
          items: [
            { label: "API Reference", to: "/api/skulk-api" },
            {
              label: "TypeScript API",
              href: "https://foxlight-foundation.github.io/Skulk/typedoc/",
            },
          ],
        },
        {
          title: "Links",
          items: [
            {
              label: "GitHub",
              href: "https://github.com/Foxlight-Foundation/Skulk",
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Foxlight Foundation.`,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
