// Copyright 2025 Foxlight Foundation

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "api-guide",
        "model-store",
        "kv-cache-backends",
        "architecture",
      ],
    },
  ],

  // docusaurus-plugin-openapi-docs writes MDX into docs/api/; autogenerated
  // picks it up and builds the sidebar from the tag groups.
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
};

export default sidebars;
