// Copyright 2025 Foxlight Foundation

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The OpenAPI plugin generates a sidebar definition that uses category links
// with tag pages.  Importing it directly (instead of autogenerated) ensures
// the tag pages are recognised as category index pages so
// useCurrentSidebarCategory() works at build time.
import apiSidebar from "./docs/api/sidebar";

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "doc",
      id: "everything-different",
      label: "Everything Different About Skulk",
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "api-guide",
        "model-store",
        "kv-cache-backends",
        "model-cards",
        "model-capabilities",
        {
          type: "category",
          label: "Model Behaviors",
          items: [
            "model-behaviors/gemma4",
            "model-behaviors/gpt-oss",
            "model-behaviors/deepseek-v32",
          ],
        },
        "architecture",
      ],
    },
  ],

  apiSidebar,
};

export default sidebars;
